apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-record-service-blue
  labels:
    app: patient-record-service
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-record-service
      version: blue
  template:
    metadata:
      labels:
        app: patient-record-service
        version: blue
    spec:
      containers:
        - name: patient-record-service
          image: gcr.io/infra-odyssey-445416-h1/patient-record-service:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/patient-record-service/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/patient-record-service/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-record-service-green
  labels:
    app: patient-record-service
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-record-service
      version: green
  template:
    metadata:
      labels:
        app: patient-record-service
        version: green
    spec:
      containers:
        - name: patient-record-service
          image: gcr.io/infra-odyssey-445416-h1/patient-record-service:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/patient-record-service/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/patient-record-service/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
